conf/distro/cml-base: increase image size for non-dev builds
Some boards need additional packages in initramfs also in non-dev
builds. Due to the increased image size of scarthgap, we need to take
this into account and thus, set the maximum initramfs size higher.

This fixes following error for the tqmlx2160a board:

  NOTE: Executing Tasks
  ERROR: gyroidos-cml-initramfs-1.0-r0 do_image_cpio: \
     The initramfs size 44044(K) exceeds INITRAMFS_MAXSIZE: 35000(K)

  NOTE: Executing Tasks
  ERROR: qoriq-signed-images-1.0-r0 do_image_cpio: \
     The initramfs size 65536(K) exceeds INITRAMFS_MAXSIZE: 35000(K)

Signed-off-by: Michael Weiß <michael.weiss@aisec.fraunhofer.de>