Fix revision error in tagged git URIs
Correctly sets PV using SRCPV and therefore fixing:
ERROR: uid-wrapper-1.2.8-r0 do_fetch: Bitbake Fetcher Error:
	FetchError("Recipe uses a floating tag/branch without a
	fixed SRCREV yet doesn't call bb.fetch2.get_srcrev()
	(use SRCPV in PV for OE).", None)

Signed-off-by: Johannes Wiesboeck <johannes.wiesboeck@aisec.fraunhofer.de>